### PR TITLE
Add rust checks from qumo

### PR DESCRIPTION
**Pull request by lochsh**
Tested here https://github.com/OxIonics/qumo/actions/runs/11331420260

I want to add these to `hermit`, hence motivation for moving these to `common-workflows`.

### CODE REVIEW

**Comment by mbirtwell** [comment]
We should update both qumo and the [parent_rust](https://github.com/OxIonics/base_project/blob/parent_rust/.github/workflows/check.yml) branch in base project to use this.

**Review by mbirtwell — APPROVED** [review]
Looks good.

Although I think it's worth pointing out that a pure rust project doesn't normally care about the availability of specific python versions. I would expect bozu and lady jessica to currently be fine building on ubuntu-24.04. They might care about the version of Glibc available, when it comes to deploying them, but that's about it.

**Comment by lochsh** [comment]
> Looks good.
> 
> Although I think it's worth pointing out that a pure rust project doesn't normally care about the availability of specific python versions. I would expect bozu and lady jessica to currently be fine building on ubuntu-24.04. They might care about the version of Glibc available, when it comes to deploying them, but that's about it.

Maybe I'll add an argument for the ubuntu version.

**Comment by lochsh** [comment]
> > Looks good.
> > Although I think it's worth pointing out that a pure rust project doesn't normally care about the availability of specific python versions. I would expect bozu and lady jessica to currently be fine building on ubuntu-24.04. They might care about the version of Glibc available, when it comes to deploying them, but that's about it.
> 
> Maybe I'll add an argument for the ubuntu version.

Done, and tested here https://github.com/OxIonics/qumo/actions/runs/11347102151

**Pull request merged**
